L = {}

/////////////////////////////////////// Font
////////////////////// See "font_en" file

/////////////////////////////////////// General
////////////////////// Units of measurement
L["unit.second"] = "s"
L["unit.meter"] = "m"
L["unit.millimeter"] = "mm"
L["unit.meterpersecond"] = "m/s"
L["unit.hammerunit"] = "UH" -- Unidades (de) Hammer
L["unit.decibel"] = "dB"
L["unit.rpm"] = "DPM" -- Disparos Por Minuto
L["unit.moa"] = "MDA" -- Minutos De Ángulo
L["unit.dmg"] = "de daño"
L["unit.projectiles"] = "PROY" -- Proyectiles

////////////////////// Ammo types
L["ammo.pistol"] = "Munición de pistola"
L["ammo.357"] = "Munición de Magnum"
L["ammo.smg1"] = "Munición de carabina"
L["ammo.ar2"] = "Munición de rifle"
L["ammo.buckshot"] = "Munición de escopeta"
L["ammo.sniperpenetratedround"] = "Munición de francotirador"
L["ammo.smg1_grenade"] = "Granadas de rifle"

/////////////////////////////////////// HUD
L["hud.version"] = "HUD DE SISTEMAS ARCTIC v"
L["hud.jammed"] = "¡FALLO!"
L["hud.therm_deco"] = "TEMP. CAÑÓN"

L["hud.firemode.single"] = "SEMI"
L["hud.firemode.burst"] = "RÁFAGA"
L["hud.firemode.auto"] = "AUTO"
L["hud.firemode.safe"] = "SEGURO"

L["hud.hint.bash"] = "Golpear"
L["hud.hint.bipod"] = "Alternar bípode"
L["hud.hint.breath"] = "Mantener respiración"
L["hud.hint.customize"] = "Personalizar"
L["hud.hint.cycle"] = "Ciclo"
L["hud.hint.firemode"] = "Cambiar modo de disparo"
L["hud.hint.inspect"] = "Inspeccionar"
L["hud.hint.lean"] = "Inclinarse"
L["hud.hint.peek"] = "Echar vistazo"
L["hud.hint.reload"] = "Recargar"
L["hud.hint.safe"] = "Alternar seguro"
L["hud.hint.switchsights"] = "Cambiar miras"
L["hud.hint.toggleatts"] = "Alternar accesorios"
L["hud.hint.ubgl"] = "Alternar"
L["hud.hint.zoom"] = "Cambiar zoom"

L["hud.error.missingbind"] = "\" %s \" sin asignar"

/////////////////////////////////////// Customization menu
L["customize.panel.customize"] = "ACCESORIOS"
L["customize.panel.personalize"] = "PERSONALIZAR"
L["customize.panel.stats"] = "ESTADÍSTICAS Y BALÍSTICA"
L["customize.panel.trivia"] = "CURIOSIDADES"
L["customize.panel.inspect"] = "INSPECCIONAR"
L["customize.panel.presets"] = "Preajustes"

L["customize.stats.aimtime"] = "Tiempo para apuntar"
L["customize.stats.ammo"] = "Munición"
L["customize.stats.armorpiercing"] = "Penetración de armadura"
L["customize.stats.burstdelay"] = "Tiempo entre ráfagas"
L["customize.stats.capacity"] = "Capacidad"
L["customize.stats.cyclic"] = "Cadencia de fuego cíclico"
L["customize.stats.explosive"] = "Daño explosivo"
L["customize.stats.firemodes"] = "Modos de disparo"
L["customize.stats.firepower"] = "Potencia de fuego"
L["customize.stats.freeaim"] = "Radio de la puntería libre"
L["customize.stats.muzzlevelocity"] = "Velocidad de salida"
L["customize.stats.noise"] = "Ruido"
L["customize.stats.penetration"] = "Penetración"
L["customize.stats.precision"] = "Precisión"
L["customize.stats.range"] = "Alcance"
L["customize.stats.ricochet"] = "Probabilidad de rebote"
L["customize.stats.rof"] = "Cadencia de fuego"
L["customize.stats.speed"] = "Velocidad de movimiento"
L["customize.stats.sprinttofire"] = "Tiempo de correr a disparar"
L["customize.stats.supplylimit"] = "Límite de suministros"
L["customize.stats.sway"] = "Vaivén"
L["customize.stats.triggerdelay"] = "Retraso del gatillo"

L["customize.hint.attach"] = "Acoplar"
L["customize.hint.controller"] = "Modo con mando está activo."
L["customize.hint.cursor"] = "Cursor"
L["customize.hint.cycle"] = "Cambiar ranura"
L["customize.hint.delete"] = "Borrar"
L["customize.hint.deselect"] = "Deseleccionar"
L["customize.hint.expand"] = "Expandir"
L["customize.hint.export"] = "Exportar"
L["customize.hint.favorite"] = "Añadir a favoritos"
L["customize.hint.import"] = "Importar"
L["customize.hint.install"] = "Instalar"
L["customize.hint.last"] = "Última ranura"
L["customize.hint.lastmode"] = "Último modo"
L["customize.hint.nextmode"] = "Siguiente modo"
L["customize.hint.open"] = "Abrir"
L["customize.hint.pan"] = "Mover" -- "Pan" in this context makes reference to moving the weapon preview around
L["customize.hint.quicksave"] = "Guardado rápido"
L["customize.hint.randomize"] = "Acoplar aleatorio"
L["customize.hint.recalculate"] = "Recalcular"
L["customize.hint.recenter"] = "Recentrar"
L["customize.hint.rotate"] = "Rotar"
L["customize.hint.save"] = "Guardar"
L["customize.hint.select"] = "Seleccionar"
L["customize.hint.unattach"] = "Desacoplar"
L["customize.hint.unfavorite"] = "Quitar de favoritos"
L["customize.hint.zoom"] = "Zoom"

L["customize.trivia.description"] = "Descripción"

L["customize.stats.explain.firepower"] = "El daño potencial a quemarropa."
L["customize.stats.explain.rof"] = "La cadencia de fuego del arma."
L["customize.stats.explain.cyclic"] = "La cadencia de fuego cíclica del arma. Ignora factores como el retraso de la ráfaga o los requisitos de recarga."
L["customize.stats.explain.capacity"] = "Cuanta munición puede contener el arma en el cargador + la recámara."
L["customize.stats.explain.range"] = "Alcance en el que el arma hace daño mínimo."
L["customize.stats.explain.precision"] = "La precisión del arma. Medido en minutos de ángulo (MDA)."
L["customize.stats.explain.muzzlevelocity"] = "La velocidad de salida de las balas disparadas con éste arma."
L["customize.stats.explain.ammo"] = "El tipo de munición que utiliza éste arma."
L["customize.stats.explain.penetration"] = "Cantidad de material que éste arma puede penetrar. Medido en milímetros de madera."
L["customize.stats.explain.ricochet"] = "Probabilidad máxima de que las balas de éste arma reboten."
L["customize.stats.explain.armorpiercing"] = "Cantidad de daño de éste arma ignorando completamente la mayoria de resistencias al daño."
L["customize.stats.explain.explosive"] = "Cantidad de daño explosivo que hará éste arma."
L["customize.stats.explain.speed"] = "Velocidad a la que te puedes mover mientras usas éste arma."
L["customize.stats.explain.aimtime"] = "Cuanto se tarda en apuntar con la mira desde la cadera."
L["customize.stats.explain.sprinttofire"] = "Cuanto se tarda en dejar de correr y empezar a disparar."
L["customize.stats.explain.firemodes"] = "A qué modos de disparo tiene acceso éste arma."
L["customize.stats.explain.burstdelay"] = "Cantidad de tiempo que debe transcurrir después de disparar una ráfaga para que el arma pueda volver a disparar."
L["customize.stats.explain.triggerdelay"] = "Retraso entre apretar el gatillo y disparar."
L["customize.stats.explain.noise"] = "Cómo de ruidosos son los disparos del arma."
L["customize.stats.explain.sway"] = "Cantidad de vaivén aplicada al arma."
L["customize.stats.explain.freeaim"] = "Ángulo máximo de la puntería libre. Cuanto más bajo, mejor."
L["customize.stats.explain.supplylimit"] = "Cantidad de munición que el arma puede recibir de las fuentes de munición de ARC9."

L["customize.bench.dummy"] = "PRUEBA CON MANIQUÍ BALÍSTICO"
L["customize.bench.effect"] = "EFECTO A DISTANCIA"
L["customize.bench.ballistics"] = "EVALUACIÓN DEL RENDIMIENTO BALÍSTICO TERMINAL"
L["customize.bench.precision"] = "PRUEBA DE PRECISIÓN MECÁNICA"

L["folder.back"] = "Atrás"
L["folder.deselect"] = "Deseleccionar"
L["folder.favorites"] = "Favoritos"
L["folder.select"] = "Seleccionar"

////////////////////// Automatic stats
L["autostat.enable.pre"] = "Habilita"
L["autostat.disable.pre"] = "Inhabilita"
L["autostat.enable.post"] = ""
L["autostat.disable.post"] = ""

L["autostat.aimdownsightstime"] = "Tiempo para apuntar con la mira"
L["autostat.alwaysphysbullet"] = "Siempre usa balas físicas"
L["autostat.ammopershot"] = "Munición por disparo"
L["autostat.armdamage"] = "Daño al brazo"
L["autostat.armorpiercing"] = "Penetración de armadura"
L["autostat.autoburst"] = "Disparo a ráfagas automático"
L["autostat.autoreload"] = "Recarga pasiva"
L["autostat.bash"] = "Ataques de cuerpo a cuerpo"
L["autostat.bashdamage"] = "Daño del cuerpo a cuerpo"
L["autostat.bashlungerange"] = "Alcance de la estocada cuerpo a cuerpo"
L["autostat.bashrange"] = "Alcance del cuerpo a cuerpo"
L["autostat.bashspeed"] = "Velocidad del cuerpo a cuerpo"
L["autostat.bipod"] = "Bípode"
L["autostat.bottomlessclip"] = "Cargador sin fondo"
L["autostat.breathholdtime"] = "Duración de la concentración"
L["autostat.bulletguidance"] = "Proyectiles guiados"
L["autostat.bulletguidanceamount"] = "Factor de guía"
L["autostat.canfireunderwater"] = "Disparar bajo el agua"
L["autostat.chambersize"] = "Capacidad de la recámara"
L["autostat.chestdamage"] = "Daño al pecho"
L["autostat.clipsize"] = "Capacidad del cargador"
L["autostat.cycletime"] = "Tiempo del ciclo"
L["autostat.damagemax"] = "Daño a corta distancia"
L["autostat.damagemin"] = "Daño a larga distancia"
L["autostat.damagerand"] = "Variación del daño"
L["autostat.deploytime"] = "Tiempo para desenfundar"
L["autostat.distance"] = "Distancia de la bala"
L["autostat.entitymuzzlevelocity"] = "Velocidad de salida del proyectil"
L["autostat.explosiondamage"] = "Daño de la explosión"
L["autostat.explosionradius"] = "Radio de la explosión"
L["autostat.fixtime"] = "Tiempo para desencascillar"
L["autostat.freeaimradius"] = "Radio de la puntería libre"
L["autostat.headshotdamage"] = "Daño por disparo a la cabeza"
L["autostat.heatcapacity"] = "Capacidad calorífica"
L["autostat.heatdissipation"] = "Disipación de calor"
L["autostat.heatpershot"] = "Calor por disparo"
L["autostat.hybridreload"] = "Recarga individual híbrida"
L["autostat.infiniteammo"] = "Munición infinita"
L["autostat.legdamage"] = "Daño a la pierna"
L["autostat.malfunction"] = "Encasquillamiento"
L["autostat.malfunctionmeanshotstofail"] = "Media de disparos entre fallos"
L["autostat.malfunctionwait"] = "Tiempo de espera por fallo"
L["autostat.manualaction"] = "Acción manual"
L["autostat.manualactionchamber"] = "Disparos por ciclo"
L["autostat.neverphysbullet"] = "Balas no físicas"
L["autostat.noflash"] = "Sin fogonazos"
L["autostat.num"] = "Recuento de proyectiles"
L["autostat.overheat"] = "Sobrecalentamiento"
L["autostat.overheattime"] = "Tiempo de espera por sobrecalentamiento"
L["autostat.pelletspread"] = "Dispersión de perdigones"
L["autostat.penetration"] = "Penetración de material"
L["autostat.penetrationdelta"] = "Daño tras penetración"
L["autostat.physbulletdrag"] = "Resistencia de la bala"
L["autostat.physbulletgravity"] = "Caída de bala"
L["autostat.physbulletmuzzlevelocity"] = "Velocidad de salida"
L["autostat.postburstdelay"] = "Retraso entre ráfagas"
L["autostat.pushbackforce"] = "Fuerza del retroceso"
L["autostat.rangemax"] = "Alcance máximo"
L["autostat.rangemin"] = "Alcance mínimo para hacer daño"
L["autostat.recoil"] = "Retroceso"
L["autostat.recoilautocontrol"] = "Control del retroceso"
L["autostat.recoildissipationrate"] = "Ratio de disipación del retroceso"
L["autostat.recoilkick"] = "Retroceso sentido"
L["autostat.recoilmodifiercap"] = "Retroceso acumulativo máximo"
L["autostat.recoilpatterndrift"] = "Desviación del retroceso"
L["autostat.recoilpershot"] = "Retroceso por disparo"
L["autostat.recoilrandomside"] = "Propagación horizontal del retroceso"
L["autostat.recoilrandomup"] = "Propagación vertical del retroceso"
L["autostat.recoilresettime"] = "Tiempo de reinicio del retroceso"
L["autostat.recoilside"] = "Retroceso horizontal"
L["autostat.recoilup"] = "Retroceso vertical"
L["autostat.reloadtime"] = "Tiempo de recarga"
L["autostat.ricochetanglemax"] = "Ángulo de rebote"
L["autostat.ricochetchance"] = "Probabilidad de rebote"
L["autostat.rpm"] = "Cadencia de fuego"
L["autostat.runawayburst"] = "Ráfaga incontrolable"
L["autostat.secondarysupplylimit"] = "Munición secundaria de reserva"
L["autostat.shootvolume"] = "Volumen de informe"
L["autostat.shootwhilesprint"] = "Disparar mientras se corre"
L["autostat.shotgunreload"] = "Recarga individual"
L["autostat.speed"] = "Velocidad de movimiento"
L["autostat.spread"] = "Dispersión"
L["autostat.sprinttofiretime"] = "Tiempo de correr a disparar"
L["autostat.stomachdamage"] = "Daño al estómago"
L["autostat.supplylimit"] = "Cargadores de reserva"
L["autostat.sway"] = "Vaivén"
L["autostat.triggerdelay"] = "Retraso del gatillo"
L["autostat.triggerdelaytime"] = "Tiempo del retraso del gatillo"
L["autostat.visualrecoil"] = "Retroceso visual"
L["autostat.visualrecoilpunch"] = "Golpe del retroceso visual"
L["autostat.visualrecoilroll"] = "Giro del retroceso visual"
L["autostat.visualrecoilside"] = "Retroceso visual horizontal"
L["autostat.visualrecoilup"] = "Retroceso visual vertical"

L["autostat.secondary._beforephrase"] = false
-- if true, secondary stat phrasing comes before the stat
L["autostat.secondary._divider"] = " "
-- space between the secondary phrase from the stat phrase. set true to use empty string

-- L["autostat.secondary.blindfire"] = "al disparar a ciegas"
L["autostat.secondary.bipod"] = "en bípode"
L["autostat.secondary.crouch"] = "mientras se está agachado"
L["autostat.secondary.empty"] = "en la última bala del cargador"
L["autostat.secondary.evenreload"] = "cada recarga pareja"
L["autostat.secondary.evenshot"] = "cada disparo parejo"
L["autostat.secondary.first"] = "en el primer disparo"
L["autostat.secondary.firstshot"] = "en el primero disparo"
L["autostat.secondary.heated"] = "al estar caliente"
L["autostat.secondary.hipfire"] = "disparando desde la cadera"
L["autostat.secondary.hot"] = "del calor"
L["autostat.secondary.last"] = "en la última bala del cargador"
L["autostat.secondary.lastshot"] = "en la útlima bala del cargador"
L["autostat.secondary.midair"] = "en el aire"
L["autostat.secondary.move"] = "moviéndose"
L["autostat.secondary.oddreload"] = "cada recarga impar"
L["autostat.secondary.oddshot"] = "cada disparo impar"
L["autostat.secondary.recoil"] = "del retroceso" --"With Each Shot"
L["autostat.secondary.shooting"] = "mientras se dispara"
L["autostat.secondary.sighted"] = "mientras se apunta"
L["autostat.secondary.sights"] = "en la mira"
L["autostat.secondary.silenced"] = "cuando está silenciado"
L["autostat.secondary.true"] = "cuando \"nombres reales\" está activo"
L["autostat.secondary.ubgl"] = "en el lanza granadas"

////////////////////// Blacklist menu
L["blacklist.title"] = "Lista negra de accesorios de ARC9"
L["blacklist.desc"] = "Los accesorios marcados aquí se bloquearán"
L["blacklist.blisted"] = "MARCADOS"
L["blacklist.all"] = "TODOS"
L["blacklist.id"] = "ID"
L["blacklist.name"] = "NOMBRE"
L["blacklist.filter"] = "FILTRO"

////////////////////// Incompatible addons
L["incompatible.title"] = "ARC9: EXTENSIONES INCOMPATIBLES"
L["incompatible.line1"] = "Tienes algunas extensiones que se sabe que no funcionan con ARC9."
L["incompatible.line2"] = "¡Desactívalas o espera un comportamiento defectuoso!"
L["incompatible.confirm"] = "Confirmar"
L["incompatible.wait"] = "Espera {time} segundos"
L["incompatible.never"] = "No volver a advertirme"
L["incompatible.never.hover"] = "¿De verdad entiendes las consecuencias?"
L["incompatible.never.confirm"] = "Has elegido no volver a mostrar las advertencias de compatibilidad nunca más. Si encuentras errores o comportamientos defectuosos, será responsabilidad tuya."

////////////////////// Presets
L["customize.presets.atts"] = " accesorios"
L["customize.presets.back"] = "Atrás"
L["customize.presets.cancel"] = "Cancelar"
L["customize.presets.code"] = "Código del preajuste (copiado al portapapeles)"
L["customize.presets.default"] = "Por defecto"
L["customize.presets.default.long"] = "Preajuste por defecto"
L["customize.presets.dumb"] = "¿Eres tonto?"
L["customize.presets.import"] = "Importar"
L["customize.presets.invalid"] = "¡Texto inválido!"
L["customize.presets.new"] = "Nombre del nuevo preajuste"
L["customize.presets.paste"] = "Pega código de preajuste aquí"
L["customize.presets.random"] = "Aleatorio"
L["customize.presets.save"] = "Guardar"
L["customize.presets.unnamed"] = "Sin nombre"

L["customize.presets.deldef"] = "¿De verdad quieres eliminar el preajuste por defecto \"{name}\"?"
L["customize.presets.deldef2"] = "Tendrás que reiniciar el arma en las opciones de desarrollo para recuperárlo."
L["customize.presets.yes"] = "Sí"

////////////////////// Tips
L["tips.arc-9"] = "Es ARC9, no ARC-9 ni Arc9."
L["tips.blacklist"] = "¡Puedes añadir accesorios a una lista negra! Consulta la descripción de la página de Workshop de ARC9 para más información."
L["tips.bugs"] = "Informa de errores en el servidor de Discord oficial, o aún mejor, abre una propuesta en Github."
L["tips.custombinds"] = "Las combinaciones de teclas de ARC9 pueden ser reemplazas por asignaciones de teclas própias. ¡Escribe +arc9_ para encontrar las asignaciones disponibles!"
L["tips.cyberdemon"] = "Para matar al terrorista, dispárale hasta que esté muerto."
L["tips.description"] = "Aconsejamos leer las descripciones de las extensiones antes de comentar."
L["tips.development"] = "¿Quieres desarrollar contenido de ARC9? ¡El servidor de Discord oficial tiene muchos recursos para ayudarte!"
L["tips.discord"] = "¡Únete a Diamond Doves en Discord! El enlace se encuentra en la descripción de ARC9 y en la parte superior del menú de ajustes."
L["tips.external"] = "Si estás usando la versión de Github de ARC9, ¡asegúrate de actualizarla con frencuencia!"
L["tips.hints"] = "Deja el HUD de ARC9 encendido para ver las pistas de los controles."
L["tips.lean"] = "Para inclinarte manualmente, asigna teclas a +alt1 y +alt2."
L["tips.love"] = "¡No dudes decirle a los desarrolladores que aprecias su trabajo! Nos ayuda mucho a seguir adelante."
L["tips.m9k"] = "¡Échale un vistazo a las armas M9K!"
L["tips.official"] = "Descarga ARC9 únicamente de fuentes oficiales. ¡Las subidas de terceros podrían ser maliciosas o estar desactualizadas!"
L["tips.presets"] = "¡Comparte tus preajustes favoritos con tus amigos exportándolos!"
L["tips.settings"] = "Puedes desactivar éstos consejos, y mucho más, en los ajustes de ARC9. ¡Haz clic en el botón de la esquina superior izquierda!"
-- L["tips.tacrp"] = "¿Has probado ya la base Tactical RP?"
L["tips.tips"] = "Los consejos tienen un orden fijo. Sigue leyendo y acabarás viéndolos todos."
L["tips.tolerance"] = "Todas las bases de armas funcionan bien juntas. No hay necesidad de favoritismos."

////////////////////// Other
L["atts.favourites"] = "Favoritos"
L["atts.filter"] = "Filtrar"

/////////////////////////////////////// Settings menu
-- Use this method to localize convars in settings menu:
-- settings.convar.title = "Convar Title"
-- settings.convar.desc = "Convar Description"

L["settings.title"] = "Ajustes de ARC9"
L["settings.desc"] = "Descripción"

L["settings.default_convar"] = "Valor predeterminado"
L["settings.convar_server"] = "Variable del servidor"
L["settings.convar_client"] = "Variable del cliente"

////////////////////// General
L["settings.tabname.general"] = "General"

L["settings.general.client"] = "Cliente"
L["settings.truenames.title"] = "Nombres reales"
L["settings.truenames.desc"] = "Establece si se usan los nombres reales de las armas o los nombres ficticios hechos por los desarrolladores. No todas las armas hace uso de ésto."
L["settings.resetsettings.cl.title"] = "Restablecer todos los ajustes del CLIENTE"

L["settings.general.server"] = "Servidor"
L["settings.truenames_default.title"] = "Nombres reales por defecto"
L["settings.truenames_default.desc"] = "Establece el modo por defecto de los nombres reales en el servidor. Todos los jugadores usando \"Por defecto\" preferiblemente utilizarán éste valor."
L["settings.truenames_enforced.title"] = "Forzar nombres reales por defecto"
L["settings.truenames_enforced.desc"] = "Establece el forzar a todos los jugadores a usar el valor del parámetro del servidor para los nombres reales."

L["settings.resetsettings.sv.title"] = "Restablecer todos los ajustes del SERVIDOR"

L["settings.reset"] = "¡Restablecer!"

////////////////////// Performance
L["settings.tabname.performance"] = "Rendimiento"

-- L["settings.optics.cheapscopes.title"] = "Cheap Scopes"
-- L["settings.optics.cheapscopes.desc"] = "A cheap RT scope implementation by zooming your whole view to aim, instead of rendering world again in a scope. Significantly increases performance on large maps."

L["settings.performance.important"] = "De mayor impacto en el rendimiento"
L["settings.cheapscopes.title"] = "Miras baratas"
L["settings.cheapscopes.desc"] = "Una implementación barata de miras RT haciendo zoom en toda la vista para apuntar, en vez de dibujar de nuevo el mundo en la mira. Aumenta significativamente el rendimiento en mapas grandes."
L["settings.tpik.title"] = "TPIK"
L["settings.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) es un sistema que permite a la mayoría de armas mostrar posiciones de manos, animaciones de disparo y recarga detalladas e igual que en primera persona, en tercera persona.\n\nConfigúralo en la pestaña Visual."
L["settings.allflash.title"] = "Todas las linternas"
L["settings.allflash.desc"] = "Dibuja completamente todas las linternas de otros jugadores.\n\nMuy caro en servidores."

L["settings.performance.blur.title"] = "Difuminado"
L["settings.cust_blur.title"] = "Fondo del menú"
L["settings.cust_blur.desc"] = "Difumina el fondo del menú de personalización."
L["settings.fx_reloadblur.title"] = "Mientras se recarga"
L["settings.fx_reloadblur.desc"] = "Difumina el mundo mientras se está recargando."
L["settings.fx_animblur.title"] = "Mientras se prepara"
L["settings.fx_animblur.desc"] = "Difumina el mundo mientras se desenfunda el arma por primera vez."
L["settings.fx_rtblur.title"] = "En miras telescópicas"
L["settings.fx_rtblur.desc"] = "Difumina el mundo mientras se está usando una mira telescópica."
L["settings.fx_adsblur.title"] = "Mientras se apunta"
L["settings.fx_adsblur.desc"] = "Difumina el mundo mientras se apunta."

L["settings.performance.shelleject.title"] = "Expulsión de casquillos"
L["settings.eject_fx.title"] = "Efectos de humo"
L["settings.eject_fx.desc"] = "Producir efectos de humo a partir de los casquillos expulsados, donde el arma admita esta característica."
L["settings.eject_time.title"] = "Añadir tiempo de vida"
L["settings.eject_time.desc"] = "Permitir a los casquillos permanecer en el mundo durante más tiempo. Puede ser caro."

L["settings.performance.fx.title"] = "Efectos"
L["settings.muzzle_light.title"] = "Fogonazo"
L["settings.muzzle_light.desc"] = "Permite que los fogonazos producidos al disparar el arma emitan luz."
L["settings.muzzle_others.title"] = "Fogonazos de otros"
L["settings.muzzle_others.desc"] = "Habilita los fogonazos de las armas de otros jugadores."

////////////////////// Optics
L["settings.tabname.optics"] = "Miras"

L["settings.optics.control"] = "Control"
L["settings.optics.sensmult.title"] = "Multiplicar sensibilidad apuntando"
L["settings.optics.sensmult.desc"] = "Multiplica la sensibilidad de la vista por esta cantidad mientras se apunta.\nCuanto menor sea el valor, más baja será la sensibilidad.\nÚtil cuando se usan mandos, o si es usuario simplemente quiere bajas la sensibilidad apuntando."
L["settings.optics.compensate_sens.title"] = "Compensar sensibilidad"
L["settings.optics.compensate_sens.desc"] = "Compensar sensibilidad por amplificación."
L["settings.optics.toggleads.title"] = "Alternar apuntado"
L["settings.optics.toggleads.desc"] = "Apuntar alternará la mira."

L["settings.optics.color"] = "Color"
L["settings.optics.reflex.title"] = "Miras réflex"
L["settings.optics.reflex.desc"] = "Color a usar en miras réflex/holográficas.\n\nNo todas las miras admiten esta característica."
L["settings.optics.scope.title"] = "Miras telescópicas"
L["settings.optics.scope.desc"] = "Color a usar en miras telescópicas.\n\nNo todas las miras admiten esta característica."

////////////////////// Crosshair
L["settings.tabname.crosshair"] = "Punto de mira"

L["settings.crosshair.crosshair"] = "Punto de mira"
L["settings.crosshair.cross_enable.title"] = "Habilitar punto de mira"
L["settings.crosshair.cross_enable.desc"] = "Habilita el punto de mira. Algunas armas no te permitirán usar el punto de mira."
L["settings.crosshair.cross.title"] = "Color del punto de mira"
L["settings.crosshair.cross.desc"] = "El color de tu punto de mira."
L["settings.crosshair.cross_size_mult.title"] = "Tamaño del punto de mira"
L["settings.crosshair.cross_size_mult.desc"] = "Multiplica el tamaño del punto de mira."
L["settings.crosshair.cross_size_dot.title"] = "Tamaño del punto central"
L["settings.crosshair.cross_size_dot.desc"] = "Multiplica el tamaño del punto central."
L["settings.crosshair.cross_size_prong.title"] = "Tamaño de las puntas"
L["settings.crosshair.cross_size_prong.desc"] = "Multiplica el tamaño de las puntas exteriores."
L["settings.crosshair.crosshair_static.title"] = "Punto de mira estático"
L["settings.crosshair.crosshair_static.desc"] = "Habilita el punto de mira estático, que no se mueve al disparar."
L["settings.crosshair.crosshair_force.title"] = "Forzar punto de mira"
L["settings.crosshair.crosshair_force.desc"] = "Fuerza el punto de mira incluso en armas que no quieren que lo veas.\n\nOpción del servidor."
L["settings.crosshair.crosshair_target.title"] = "Punto de mira rojo en objetivo"
L["settings.crosshair.crosshair_target.desc"] = "Hace que el punto de mira se vuelva rojo cuando se apunta a un objetivo.\nAdemás también activa la puntería asistida si está activa."
L["settings.crosshair.crosshair_peeking.title"] = "Mostrar punto de mira al echar un vistazo"
L["settings.crosshair.crosshair_peeking.desc"] = "Muestra el punto de mira cuando al apuntar se usa la característica de echar un vistazo."

////////////////////// Customization
L["settings.tabname.hud_cust"] = "Personalización"

L["settings.hud_cust.hud"] = "HUD"
L["settings.hud_cust.hud_scale.title"] = "Escala del HUD"
L["settings.hud_cust.hud_scale.desc"] = "Multiplicador de escala para el HUD de ARC9."
L["settings.hud_cust.hud_deadzonex.title"] = "Ancho de la zona muerta del HUD"
L["settings.hud_cust.hud_deadzonex.desc"] = "\"Zona muerta\" horizontal del menú de personalización y panel del HUD.\nÚtil para monitores ultra anchos."
L["settings.hud_cust.hud_color.title"] = "Color del HUD"
L["settings.hud_cust.hud_color.desc"] = "Color de realce para el HUD.\nEl color de acento."
-- L["settings.hud_cust.language_id.title"] = "Idioma"
-- L["settings.hud_cust.language_id.desc"] = "Paquete de idioma a usar para ARC9."
L["settings.hud_cust.hud_darkmode.title"] = "Tema oscuro"
L["settings.hud_cust.hud_darkmode.desc"] = "Habilita los colores oscures en el HUD en lugar del gris claro y desactiva el efecto de viñeta en el fondo."
L["settings.hud_cust.cust_light.title"] = "Habilitar luz"
L["settings.hud_cust.cust_light.desc"] = "Habilita la iluminación del arma en el menú de personalización.\n\nLo mismo que el botón cerca del de ajustes."
L["settings.hud_cust.cust_light_brightness.title"] = "Brillo de la luz"
L["settings.hud_cust.cust_light_brightness.desc"] = "Cómo de brillante será la luz del panel de personalización.\n\n¡No te olvides de encenderla primero!"

L["settings.hud_cust.customization"] = "Personalización"
L["settings.hud_cust.cust_hints.title"] = "Pistas"
L["settings.hud_cust.cust_hints.desc"] = "Habilita pistas en el menú de personalización."
-- L["settings.hud_cust.cust_roll_unlock.title"] = "Unlock Roll" -- NOT USED ANYMORE
-- L["settings.hud_cust.cust_roll_unlock.desc"] = "Allow weapon roll in the customization menu.\n\nMight look and control not the best way." -- NOT USED ANYMORE
L["settings.hud_cust.cust_tips.title"] = "Consejos"
L["settings.hud_cust.cust_tips.desc"] = "Consejos sobre ARC9 cerca de las pistas."
L["settings.hud_cust.cust_exit_reset_sel.title"] = "Reiniciar selección al salir"
L["settings.hud_cust.cust_exit_reset_sel.desc"] = "Al salir del menú de personalización se reiniciará la selección de la ranura activa."

////////////////////// Game HUD
L["settings.tabname.hud_game"] = "HUD del juego"

L["settings.hud_game.lcd"] = "Panel LCD"
L["settings.hud_game.hud_arc9.title"] = "Habilitar HUD"
L["settings.hud_game.hud_arc9.desc"] = "Habilitar HUD para armas ARC9."
L["settings.hud_game.hud_always.title"] = "En todas las armas"
L["settings.hud_game.hud_always.desc"] = "Habilita el HUD en todas las armas."
L["settings.hud_game.hud_compact.title"] = "Modo compacto"
L["settings.hud_game.hud_compact.desc"] = "Apariencia compacta para el panel del HUD."
L["settings.hud_game.hud_nohints.title"] = "Deshabilitar consejos"
L["settings.hud_game.hud_nohints.desc"] = "Deshabilita completamente los consejos. No se mostrarán ni en el HUD 3D, ni en el HUD 2D."
L["settings.hud_game.hud_keephints.title"] = "Mantener pistas"
L["settings.hud_game.hud_keephints.desc"] = "Mostrar las pistas de controles de ARC9 encima del panel del HUD."
L["settings.hud_game.hud_force_disable.title"] = "Forzar la inhabilitación del HUD"
L["settings.hud_game.hud_force_disable.desc"] = "Inhabilita el HUD de ARC9 para todos los jugadores. No afecta a las pistas."

L["settings.hud_game.killfeed"] = "Killfeed"
L["settings.hud_game.killfeed_enable.title"] = "Iconos del killfeed"
L["settings.hud_game.killfeed_enable.desc"] = "Habilita la generación automática de iconos de killfeed para armas ARC9."
L["settings.hud_game.killfeed_dynamic.title"] = "Actualización dinámica"
L["settings.hud_game.killfeed_dynamic.desc"] = "Los iconos del killfeed se generarán tras cada muerte.\n\nDesactívalo si quieres conseguir esos 0.1 fps."
L["settings.hud_game.killfeed_color.title"] = "Iconos a todo color"
L["settings.hud_game.killfeed_color.desc"] = "Los iconos generados dinámicamente están totalmente coloreados."

L["settings.hud_game.breath"] = "Respiración"
L["settings.hud_game.breath_hud.title"] = "HUD de respiración"
L["settings.hud_game.breath_hud.desc"] = "Mostrar una barra que muestra la respiración restante mientras estabilizas tu arma al apuntar."
L["settings.hud_game.breath_pp.title"] = "Post-procesado manteniendo la respiración"
L["settings.hud_game.breath_pp.desc"] = "Mantener la respiración también añadirá efectos de post-procesado en tu pantalla."
L["settings.hud_game.breath_sfx.title"] = "Sonido de mantener la respiración"
L["settings.hud_game.breath_sfx.desc"] = "Al mantener la respiración se reproducirán efectos de sonido asociados."

L["settings.hud_game.centerhint"] = "Consejos"
L["settings.hud_game.centerhint_reload.title"] = "Mostrar consejo de recarga"
L["settings.hud_game.centerhint_reload.desc"] = "Muestra un consejo de recarga cuando quede poca munición."
L["settings.hud_game.centerhint_reload_percent.title"] = "Porcentaje del cargador"
L["settings.hud_game.centerhint_reload_percent.desc"] = "Muestra un consejo de recarga cuando el cargador actual se encuentra en éste valor porcentual."
L["settings.hud_game.centerhint_bipod.title"] = "Mostrar alternar bípode"
L["settings.hud_game.centerhint_bipod.desc"] = "Muestra un consejo cuando el bípode puede ser alternado."

////////////////////// NPCs
L["settings.tabname.npc"] = "PNJ"

L["settings.npc.weapons"] = "Armas en PNJ"
L["settings.npc.npc_equality.title"] = "Igualdad de daño"
L["settings.npc.npc_equality.desc"] = "Los PNJ hace tanto daño como los jugadores.\n\nEsta es una variable del servidor."
L["settings.npc.npc_spread.title"] = "Dispersión en los PNJ"
L["settings.npc.npc_spread.desc"] = "Multiplicador para cómo de inprecisos serán los PNJ al disparar."
L["settings.npc.npc_atts.title"] = "Dar accesorios"
L["settings.npc.npc_atts.desc"] = "Las armas ARC9 creadas o entregadas recibirán una serie de accesorios de manera aleatoria.\n\nEsta es una variable del servidor."
L["settings.npc.npc_autoreplace.title"] = "Reemplazar armas de los PNJ"
L["settings.npc.npc_autoreplace.desc"] = "Reemplaza las armas de los PNJ con armas ARC9 escogidas aleatoriamente.\n\nEsta es una variable del servidor."
L["settings.npc.replace_spawned.title"] = "Reemplaza armas del suelo"
L["settings.npc.replace_spawned.desc"] = "Reemplaza las armas de HL2 del mapa (o creadas) con armas ARC9 escogidas aleatoriamente.\n\nEsta es una variable del servidor."
L["settings.npc.npc_give_weapons.title"] = "Jugadores pueden dar armas"
L["settings.npc.npc_give_weapons.desc"] = "Los jugadores son capaces de darle armas a los PNJ pulsando E.\n\nEsta es una variable del servidor."

////////////////////// Gameplay
L["settings.tabname.gameplay"] = "Jugabilidad"

L["settings.gameplay.controls"] = "Controles"
L["settings.gameplay.toggleads.title"] = "Alternar apuntado"
L["settings.gameplay.toggleads.desc"] = "El apuntar será alternado."
L["settings.gameplay.autolean.title"] = "Inclinación automática"
L["settings.gameplay.autolean.desc"] = "Al apuntar se intentará inclinarte si es posible."
L["settings.gameplay.autoreload.title"] = "Recarga automática"
L["settings.gameplay.autoreload.desc"] = "Las armas ARC9 vacías se recargarán automáticamente."
L["settings.gameplay.togglelean.title"] = "Alternar inclinación"
L["settings.gameplay.togglelean.desc"] = "Al pulsar las teclas de inclinarse alternará la inclinación en vez de necesitar que las mantengas pulsadas.\n\nNo funciona bien en conjunto con la inclinación automática. Si estás usando inclinación alternada, deberías desactivar la inclinación automática."
L["settings.gameplay.togglepeek.title"] = "Alternar echar vistazo"
L["settings.gameplay.togglepeek.desc"] = "Al pulsar la tecla de echar vistazo alternarás el echar vistazo en vez de necesitar que la mantengas pulsada."
L["settings.gameplay.togglepeek_reset.title"] = "Reiniciar estado de echar vistazo después de apuntar"
L["settings.gameplay.togglepeek_reset.desc"] = "(Solo funciona si Alternar echar vistazo está activo)\nEl estado de echar vistazo no se retendrá al dejar de apuntar."
L["settings.gameplay.togglebreath.title"] = "Alternar mantener respiración"
L["settings.gameplay.togglebreath.desc"] = "Pulsar la tecla de mantener respiración alternará mantener la respiración en vez de necesitar que mantengas la tecla."

L["settings.gameplay.mechanics"] = "Mecánicas de juego"
L["settings.gameplay.infinite_ammo.title"] = "Munición infinita"
L["settings.gameplay.infinite_ammo.desc"] = "Las armas tienen munición infinita.\n\nEsta es una variable del servidor."
L["settings.gameplay.realrecoil.title"] = "Retroceso visual físico"
L["settings.gameplay.realrecoil.desc"] = "Ciertas armas que estén preparadas para esta característica experimentarán elevación física del cañón, lo que significa que dispararán donde su modelo de vista apunta en vez de al centro de la pantalla. Muy importante para los esquemas de equilibrio de algunos paquetes de armas.\n\nEsta es una variable del servidor."
L["settings.gameplay.lean.title"] = "Inclinación"
L["settings.gameplay.lean.desc"] = "Si los jugadores pueden inclinarse con +alt1 y +alt2, incluyendo la inclinación automática.\n\nEsta es una variable del servidor."
L["settings.gameplay.mod_sway.title"] = "Vaivén"
L["settings.gameplay.mod_sway.desc"] = "Las armas tendrán vaivén, si es que están preparadas para usarlo.\n\nEsta es una variable del servidor."
L["settings.gameplay.mod_freeaim.title"] = "Puntería libre"
L["settings.gameplay.mod_freeaim.desc"] = "Las armas tendrán puntería libre y no siempre dispararán en el centro de la pantalla.\n\nEsta es una variable del servidor."
L["settings.gameplay.mod_bodydamagecancel.title"] = "Anulación del daño al cuerpo"
L["settings.gameplay.mod_bodydamagecancel.desc"] = "Anula el multiplicador por defecto de daño al cuerpo. Desactívalo solamente si estás usando otra extensión que proporcione éste tipo de funcionalidad.\nPor ejemplo, extensiones que cambien los multiplicadores de daño a las extremidades.\n\nEsta es una variable del servidor."
L["settings.gameplay.breath_slowmo.title"] = "Mantener respiración a cámara lenta"
L["settings.gameplay.breath_slowmo.desc"] = "Mantener la respiración ralentizará el tiempo.\n\nSolamente disponible en una partida en solitario."
L["settings.gameplay.manualbolt.title"] = "Ciclado automático"
L["settings.gameplay.manualbolt.desc"] = "Las armas de cerrojo configuradas para esta característica solamente accionará el cerrojo cuando se pulse la R y no cuando la tecla de atacar se suelte."
L["settings.gameplay.never_ready.title"] = "Sin animaciones de preparación"
L["settings.gameplay.never_ready.desc"] = "Desactiva las animaciones de preparación cuando se desenfunda un arma.\n\nEsta es una variable del servidor."
L["settings.gameplay.recoilshake.title"] = "Sacudida del campo de visión por retroceso"
L["settings.gameplay.recoilshake.desc"] = "Ajusta el campo de visión cuando se dispara"
L["settings.gameplay.equipment_generate_ammo.title"] = "Tipos de munición únicos para equipos"
L["settings.gameplay.equipment_generate_ammo.desc"] = "Hay un límite de 255 tipos de munición, y desactivar esta opción puede ayudar a arreglar algunos problemas si tienes muchas extensiones.\n\nEsta es una variable del servidor.\n\nRequiere reinicio."

-- ??
L["settings.gameplay.mult_defaultammo.title"] = "Munición de reserva por defecto"
L["settings.gameplay.mult_defaultammo.desc"] = "¿Cuántos cargadores/granadas/equipos se dan al jugador cuando coge el arma por primera vez?\n\nEsta es una variable del servidor."
L["settings.gameplay.nearwall.title"] = "Cerca de la pared"
L["settings.gameplay.nearwall.desc"] = "No permite disparar el arma cuando se está demasiado cerca de la pared o cualquier obstáculo."

////////////////////// Visuals
L["settings.tabname.visuals"] = "Visual"

L["settings.visuals.viewmodel"] = "Modelo de vista"
L["settings.visuals.vm_bobstyle.title"] = "Estilo de balanceo"
L["settings.visuals.vm_bobstyle.desc"] = "Selecciona diferentes estilos de balanceo, al gusto de los diferentes miembros de ARC9 (y Valve Software), yendo desde el estilo más nuevo al más antiguo."
L["settings.visuals.fov.title"] = "Campo de visión"
L["settings.visuals.fov.desc"] = "Añade campo de visión al modelo de vista. Hace el modelo más grande o más pequeño. Úsalo responsablemente."
L["settings.visuals.vm_addx.title"] = "Agregar X"
L["settings.visuals.vm_addx.desc"] = "Desplaza el modelo a la derecha o a la izquierda."
L["settings.visuals.vm_addy.title"] = "Agregar Y"
L["settings.visuals.vm_addy.desc"] = "Desplaza el modelo hacia delante y hacia atrás."
L["settings.visuals.vm_addz.title"] = "Agregar Z"
L["settings.visuals.vm_addz.desc"] = "Desplaza el modelo arriba y abajo."

L["settings.visuals.cambob"] = "Balanceo de vista"
L["settings.visuals.vm_cambob.title"] = "Balanceo de vista corriendo"
L["settings.visuals.vm_cambob.desc"] = "Hace que tu cámara se mueva cuando estás corriendo."
L["settings.visuals.vm_cambobwalk.title"] = "Balanceo de vista andando"
L["settings.visuals.vm_cambobwalk.desc"] = "Hace que tu cámara se mueva ligeramente cuando andas (requiere balanceo de vista corriendo)."
L["settings.visuals.vm_cambobintensity.title"] = "Intensidad"
L["settings.visuals.vm_cambobintensity.desc"] = "Como de intenso será el balanceo."

L["settings.visuals.tpik"] = "TPIK"
L["settings.visuals.tpik.title"] = "Habilitar TPIK"
L["settings.visuals.tpik.desc"] = "TPIK (Third Person Inverse Kinematics) es un sistema que permite a la mayoría de armas mostrar posiciones de manos, animaciones de disparo y recarga detalladas e igual que en primera persona, en tercera persona."
L["settings.visuals.tpik_others.title"] = "TPIK de otros jugadores"
L["settings.visuals.tpik_others.desc"] = "Muestra TPIK de otros jugadores que no seas tú. Impacta negativamente al rendimiento."
L["settings.visuals.tpik_framerate.title"] = "Tasa de fotogramas para TPIK"
L["settings.visuals.tpik_framerate.desc"] = "Tasa de fotogramas máxima a la que puede funcionar TPIK. Asígnalo a 0 para que sea ilimitado."

////////////////////// Bullet Physics
L["settings.tabname.bullets"] = "Físicas de balas"

L["settings.bullets.bullets"] = "Físicas de balas"
L["settings.bullets.bullet_physics.title"] = "Balas físicas"
L["settings.bullets.bullet_physics.desc"] = "Las armas que admitan esta característica dispararán balas fisicas, que tendrán caída, tiempo de recorrido y resistencia.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_gravity.title"] = "Gravedad"
L["settings.bullets.bullet_gravity.desc"] = "Multiplicador de la gravedad de las balas.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_drag.title"] = "Resistencia"
L["settings.bullets.bullet_drag.desc"] = "Multiplicador de la resistencia de las balas.\n\nEsta es una variable del servidor."
L["settings.bullets.ricochet.title"] = "Rebote"
L["settings.bullets.ricochet.desc"] = "Balas disparadas desde ciertas armas podrán a veces rebotar en superfícies y seguir viajando y causando daño.\n\nEsta es una variable del servidor."
L["settings.bullets.mod_penetration.title"] = "Penetración"
L["settings.bullets.mod_penetration.desc"] = "Balas disparadas desde ciertas armas pueden penetrar superfícies y causar daño a lo que sea que esté al otro lado.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_lifetime.title"] = "Tiempo de vida"
L["settings.bullets.bullet_lifetime.desc"] = "Tiempo en segundo tras el cual se borrará una bala.\n\nEsta es una variable del servidor."
L["settings.bullets.bullet_imaginary.title"] = "Balas imaginarias"
L["settings.bullets.bullet_imaginary.desc"] = "Las balas parecerán viajar por la \"skybox\", más allá de los límites del mapa."

////////////////////// Attachments
L["settings.tabname.attachments"] = "Accesorios"

L["settings.attachments.customization"] = "Personalización"
L["settings.attachments.atts_nocustomize.title"] = "Inhabilitar personalización"
L["settings.attachments.atts_nocustomize.desc"] = "Inhabilita toda personalización disponible desde el menú de personalización.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_max.title"] = "Máximo de accesorios"
L["settings.attachments.atts_max.desc"] = "El máximo número de accesorios que se le pueden poner a un arma, incluyendo accesorios cosméticos.\n\nEsta es una variable del servidor."
L["settings.attachments.autosave.title"] = "Autoguardado"
L["settings.attachments.autosave.desc"] = "Tus últimas opciones de personalización de un arma se guardarán y se aplicarán automáticamente la próxima vez que vuelvas a hacer aparecer ése arma."
L["settings.attachments.blacklist.title"] = "Menú de la lista negra"
L["settings.attachments.blacklist.open"] = "Abrir"

L["settings.attachments.inventory"] = "Inventario"
L["settings.attachments.free_atts.title"] = "Accesorios gratuitos"
L["settings.attachments.free_atts.desc"] = "Los accesorios se pueden usar sin tener que recogerlos primero.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_lock.title"] = "Uno para todos"
L["settings.attachments.atts_lock.desc"] = "Recoger una instancia de un accesorio te permite usarlo infinitas veces en todas tus armas.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_loseondie.title"] = "Perderlo al morir"
L["settings.attachments.atts_loseondie.desc"] = "Tu inventario de accesorios será perdido cuando mueras.\n\nEsta es una variable del servidor."
L["settings.attachments.atts_generateentities.title"] = "Generar entidades"
L["settings.attachments.atts_generateentities.desc"] = "Generar entidades que pueden ser creadas, permitiéndote recoger accesorios cuando accesorios gratuitos está desactivado.\n\nPuede aumentar el tiempo de carga.\n\nEsta es una variable del servidor."

////////////////////// Modifiers
L["settings.tabname.modifiers"] = "Modificadores"

-- L["settings.modifiers.quick.desc"] = "We are a little sorry but we couldn't finish them to release. You will have to use advanced modifiers in  spawnmenu > Options > ARC9 > Modifiers  for now."

L["settings.modifiers.quick.desc"] = " "

L["settings.modifiers.quick.title"] = "Modificadores rápidos de estadísticas"
L["settings.mod_damage.title"] = "Daño"
L["settings.mod_spread.title"] = "Dispersión"
L["settings.mod_recoil.title"] = "Retroceso"
L["settings.mod_visualrecoil.title"] = "Retroceso visual"
L["settings.mod_adstime.title"] = "Tiempo para apuntar"
L["settings.mod_sprinttime.title"] = "Tiempo de correr a disparar"
L["settings.mod_damagerand.title"] = "Variación de daño"
L["settings.mod_muzzlevelocity.title"] = "Velocidad de salida"
L["settings.mod_rpm.title"] = "DPM" -- Disparos Por Minuto
L["settings.mod_headshotdamage.title"] = "Daño a la cabeza"
L["settings.mod_malfunction.title"] = "Probabilidad de fallo"

////////////////////// Controller
L["settings.tabname.controller"] = "Mando"

L["settings.controller.misc"] = "Misceláneo"
L["settings.controller.misc.desc"] = "Debería haber un botón que abrirá el panel con la configuración avanzada del mando, pero por ahora está en menú de creación > Opciones > ARC9 > Mando."
L["settings.controller.controller.title"] = "Activar modo Super mando"
L["settings.controller.controller.desc"] = "Habilita acciones personalizadas compatibles con el mando.\n'Usar' es M1.\n'Recargar' es M2.\nAsigna acciones a glifos en las opciones secretas."
-- L["settings.controller.controller_rumble.title"] = "Rumble"
-- L["settings.controller.controller_rumble.desc"] = "Enable controller rumble as long as Fesiug's DLL mod is loaded.\n\ngithub.com/Fesiug/\ngmod-sinput"
L["settings.controller.controller_config.title"] = "Configuración avanzada"
L["settings.controller.controller_config.content"] = "Abrir panel"
L["settings.controller.controller_config.desc"] = "Abre el panel de configuración avanzada del mando."

////////////////////// Aim Assist
L["settings.tabname.aimassist"] = "Puntería asistida"
L["settings.tabname.aimassist.desc"] = "Puedes habilitar la puntería asistida si tienes problemas manteniendo la mira en tu objetivo, o si simplemente prefieres no tener que esforzarte cuando disparas a tus objetivos."

L["settings.aimassist.enable.title"] = "Habilitar puntería asistida"
L["settings.aimassist.enable.desc"] = "Habilita la característica de puntería asistida que ralentiza tu sensibilidad cuando apuntas a un objetivo válido.\n\nEsta es una variable del servidor.\n\nTambién requiere tener la puntería asistida en el CLIENTE."

L["settings.aimassist.enable_client.desc"] = "Habilita la característica de puntería asistida que ralentiza tu sensibilidad cuando apuntas a un objetivo válido.\n\nTambién requiere tener la puntería asistida en el SERVIDOR."

L["settings.aimassist.lockon.title"] = "Fijación"
L["settings.aimassist.lockon.desc"] = "Habilita la asistencia de fijación que mueve tu puntería hacia un objetivo válido.\n\nRequiere que la asistencia de fijación esté permitida."

L["settings.aimassist.intensity.title"] = "Intensidad"
L["settings.aimassist.intensity.desc"] = "Como de intensa es la asistencia de apuntado.\n\nEsta es una variable del servidor."

L["settings.aimassist.cone.title"] = "Cono"
L["settings.aimassist.cone.desc"] = "Como de cerca o lejos debes mirar hacia el objetivo antes de que la puntería asistida se active.\n\nEsta es una variable del servidor."

L["settings.aimassist.head.title"] = "Fijar en la cabeza"
L["settings.aimassist.head.desc"] = "Si la puntería asistida debería fijar la cabeza del objetivo en vez de su pecho.\n\nEsta es una variable del servidor."

L["settings.aimassist.lockon_allow.title"] = "Permitir asistencia de fijación"
L["settings.aimassist.lockon_allow.desc"] = "Permite el uso de la asistencia de fijación.\n\nEsta es una variable del servidor."

////////////////////// Asset Caching
L["settings.tabname.caching"] = "Almacen. de recursos"
L["settings.caching.title"] = "Almacenamiento de recursos"
L["settings.caching.desc"] = "¡Puedes almacenar algunos recursos de ARC9 (guardarlos en memoria sin tener que cargarlo mientras juegas) y así evitar que se congele la partida de forma intermitente para una jugabilidad más cómoda!\n\nLa verdad es que deberías activar algunas cosas si tu GMod está instalado en un HDD."

L["settings.caching.precache_sounds_onfirsttake.title"] = "Al equiparse por primera vez: Almacenar sonidos de arma"
L["settings.caching.precache_sounds_onfirsttake.desc"] = "Almacena todos los sonidos solamente del arma que acabas de recibir (exceptuando sonidos de recarga).\n\nNada impactante, pero ayuda a prevenir que se congele el juego cuando dispares."

L["settings.caching.precache_attsmodels_onfirsttake.title"] = "Al equiparse por primera vez: Almacenar todos los accesorios"
L["settings.caching.precache_attsmodels_onfirsttake.desc"] = "Almacena todos los modelos de todos los accesorios de ARC9 cuando cualquier arma ARC9 se equipe por primera vez.\n\nCausa una congelación bastante grande, especialmente si tienes muchas armas."
L["settings.caching.precache_wepmodels_onfirsttake.title"] = "Al equiparse por primera vez: Almacena todos los modelos de armas"
L["settings.caching.precache_wepmodels_onfirsttake.desc"] = "Almacena los modelos de vista de todas las armas ARC9 cuando cualquier arma ARC9 se equipe por primera vez.\n\nCausa una congelación VERDADERAMENTE GRANDE, especialmente si tienes muchas armas."

L["settings.caching.precache_allsounds_onstartup.title"] = "Cuando empiece la partida: Almacenar todos los sonidos de armas"
L["settings.caching.precache_allsounds_onstartup.desc"] = "Almacena todos los sonidos de todas las armas al iniciarse el servidor. (exceptuando sonidos de recarga).\n\nNo es demasiado impactante, pero de todos modos lo mejor sería usar la primera opción aquí."
L["settings.caching.precache_attsmodels_onstartup.title"] = "Cuando empiece la partida: Almacenar todos los accesorios"
L["settings.caching.precache_attsmodels_onstartup.desc"] = "Almacena todos los modelos de los accesorios de ARC9 al iniciarse el servidor.\n\nCausa un aumento bastante grande en el tiempo de carga, especialmente cuando tienes muchas armas."
L["settings.caching.precache_wepmodels_onstartup.title"] = "Cuando empiece la partida: Almacenar todos los modelos de armas"
L["settings.caching.precache_wepmodels_onstartup.desc"] = "Almacena los modelos de vista de todas las armas ARC9 al iniciarse el servidor.\n\nCausa un aumento VERDADERAMENTE GRANDE en el tiempo de carga, especialmente si tienes muchas armas."

L["settings.caching.precache_allsounds.title"] = "Todos los sonidos de armas"
L["settings.caching.precache_wepmodels.title"] = "Todos los modelos de armas"
L["settings.caching.precache_attsmodels.title"] = "Todos los modelos de accesorios"

L["settings.developer.cache"] = "Almacenar"

////////////////////// Developer
L["settings.tabname.developer"] = "Desarrollador"

L["settings.developer.developer"] = "Opciones de desarrollador"
L["settings.developer.dev_always_ready.title"] = "Prepara siempre"
L["settings.developer.dev_always_ready.desc"] = "Siempre reproduce la animación de \"preparación\" cuando se desenfunda un arma.\n\nEsta es una variable del servidor."
L["settings.developer.dev_benchgun.title"] = "Modelo de arma estático"
L["settings.developer.dev_benchgun.desc"] = "Mantén el arma donde se encuentra actualmente."
L["settings.developer.dev_crosshair.title"] = "Punto de mira de desarrollador"
L["settings.developer.dev_crosshair.desc"] = "Un punto de mira de aspecto gracioso que muestra el punto exacto de puntería y algunos números útiles.\n\nEsta es una variable del servidor, y sólo funciona para los administradores - ¡no lo uses para hacer trampas!"
L["settings.developer.dev_show_shield.title"] = "Mostrar escudo"
L["settings.developer.dev_show_shield.desc"] = "Muestra el modelo del escudo del jugador."
L["settings.developer.dev_greenscreen.title"] = "Pantalla verde"
L["settings.developer.dev_greenscreen.desc"] = "Muestra un fondo de pantalla verde en el menú de personalización para capturas de pantalla.\n\nSi estás usando HDR, ¡no olvides establecer mat_bloom_scalefactor_scalar a 0!"
L["settings.developer.reloadatts.title"] = "Recargar accesorios"
L["settings.developer.reloadlangs.title"] = "Recargar idiomas"
L["settings.developer.dev_listmyatts.title"] = "Listar mis accesorios"
L["settings.developer.dev_listanims.title"] = "Listar animaciones"
L["settings.developer.dev_listbones.title"] = "Listar huesos"
L["settings.developer.dev_listbgs.title"] = "Listar \"bodygroups\""
L["settings.developer.dev_listatts.title"] = "Listar QCAttachments"
L["settings.developer.dev_export.title"] = "Código de exportación"
L["settings.developer.dev_getjson.title"] = "JSON del arma"

L["settings.developer.presets_clear.title"] = "Limpiar datos de armas"
L["settings.developer.presets_clear.desc"] = "Borra los preajustes, todos los iconos y preajuste por defecto del arma que estás sosteniendo actualmente.\n\nAdvertencia: ¡si el menú se abre sin un arma ARC9 en las manos borrará todos los prejustes e iconos existentes de ARC9!"

L["settings.developer.clear"] = "Limpiar"
L["settings.developer.print"] = "Imprimir en consola"
L["settings.developer.reload"] = "Recargar"
